name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python Environment
      - name: Set up Python env
        run: |
          pip install -r requirements.txt

      # Train the model and run ML Pipeline     
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py

          echo "# MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "# Data Viz" > report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md
